name: CI

on:
  push:
    branches: [ "main" , "next" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install MPI and HDF5
        run: |
          sudo apt install libhdf5-dev
          sudo apt install libopenmpi-dev openmpi-common
          sudo apt install libhdf5-mpi-dev libhdf5-openmpi-dev
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd build
          ctest
