name: CI

on:
  push:
    branches: [ "main" , "next" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install MPI and HDF5
        run: |
          sudo apt update
          sudo apt install libopenmpi-dev openmpi-common
          sudo apt install libhdf5-dev libhdf5-mpi-dev libhdf5-openmpi-dev
      - name: Build
        run: |
          make 
      - name: Run tests
        run: |
          make check

