name: CI

on:
  push:
    branches: [ "main" , "next" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install MPI and HDF5
        run: |
          sudo apt install libhdf5-dev
          sudo apt install libopenmpi-dev openmpi-common
          sudo apt install libhdf5-mpi-dev libhdf5-openmpi-dev
      - name: Set up nightly Rust toolchain
        run: |
          rustup install nightly && rustup default nightly
      - name: Build
        run: |
          cd rust/
          cargo build --all --verbose
          cargo doc --all --verbose
      - name: Run tests
        run: |
          cd rust/
          cargo test --all --verbose
        
