name: CI

on:
  push:
    branches: [ "main" , "next" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install HDF5
      run: |
        sudo apt install libhdf5-dev
    - name: Set up nightly Rust toolchain
      run: |
        rustup install nightly && rustup default nightly
    - name: Build
      run: |
        cargo build --all --verbose
        cargo doc --all --verbose
    - name: Run tests
      run: |
        cargo test --all --verbose 
        
